### ISSUE TITLE
Module not found: fast-deep-equal/react

### ISSUE THREAD

**Issue by carloscalage** [michelecocuccio/simple-react-lightbox#53]
Hey mate, 

Thanks a lot for this library, really great work!

Unfortunately I'm having this issue here. I'm using yarn to install it on my project and I'm getting this error when I start my application... I'm relatively new to the react and I don't know if this is something that I needed to do?

```
./node_modules/simple-react-lightbox/dist/index.es.js
Module not found: Can't resolve 'fast-deep-equal/react' in '.../node_modules/simple-react-lightbox/dist'
```

Thanks!

**Comment by michelecocuccio** [comment]
@carloscalage hello.

When opening an issue i need to follow the following. I also need to to know if you are using the latest version of the Simple React Lightbox (3.0.2).  Also have you tried with NPM instead of yarn?
It should make a difference. Please compile the questions below.

**Describe the bug**
Please describe the bug and how/when happens. Try to be concise and describe clearly the action that you have taken prior to encountering the bug.

**Environment*
Please state if you are using Create React App, Gatsby or NextJS and their version. Include your version of Node and your version of React. Please also include the browser that you are using and possibly its version.

**To Reproduce**
Please include steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by carloscalage** [comment]
Sorry, I forgot to send those informations.

I'm using the latest version of your package and react 16.12.0. I created with Create React App and I'm using yarn tool to install my packages. 

I tried to use NPM, but I'm having conflict with yarn, so I can't tell if it's working... 

Everything was working ok, then I use "yarn add simples-react-lightbox" and then "yarn start" and I got that error message, even before using anything on my code.

What more info can I send you to help?

**Comment by michelecocuccio** [comment]
@carloscalage try do the following: 

```yarn remove simple-react-lightbox```
delete your node_modules folder
delete your yarn.lock file
```yarn```
```yarn add simple-react-lightbox```

Is quite difficult to understand what's going on :( I tried with your version of React and it works.
Can you also copy and paste your package.json file? Make sure it doesn't contain any sensitive informations, I just want to see what other packages you are using.

**Comment by carloscalage** [comment]
I fixed the problem, but I don't really know what was causing... I removed some unused depencies that I had and then I reinstalled your package and worked like a charm. If you want to know, these are the dependencies that I removed:

Antd, react-select, beautiful-react-hooks and react-transition-group.

Thanks for your time and fast support!

**Comment by michelecocuccio** [comment]
@carloscalage glad you are solved it. Sometimes unused dependencies can cause issues. It's good to keep your project clean. Glad you fixed it.

**Comment by njbarrett** [comment]
Hello - I had this issue as well, using npm, the project depends on `fast-deep-equal/react` and I had to manually include it within my package.json

**Comment by carloscalage** [comment]
Oh yeah... I forgot to say that I also added the fast-deep-equal on my project using `yarn add fast-deep-equal/react` in case anyone else is having the same problem and even with the cleaning of unused packages are still having this error message

**Comment by michelecocuccio** [comment]
> Hello - I had this issue as well, using npm, the project depends on `fast-deep-equal/react` and I had to manually include it within my package.json

Hello. The project doesn't depends on `fast-deep-equal/react` but one dependencies does. Usually, when installing a package all the other dependencies required by the other packages should be installed. Apparently this is not happening with `react-use`. I will have a look or include it as my own dependency.

Thanks
